---
title: "features"
author: "Grace Gao"
date: "3/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

## load in packages
```{r packages}
library("readxl")
library(tidyverse)
library('xml2')
library(rvest)
library(openxlsx)
library(readxl)
library(writexl)
library(dplyr)

```


####add in dataset

```{r}

one <- read_excel("features/full_new.xlsx")
two <- read_excel("features/full_new2.xlsx")
three <- read_excel("features/full_new3.xlsx")
four <- read_excel("features/full_new4.xlsx")
five <- read_excel("features/full_new5.xlsx")
six <- read_excel("features/full_new6.xlsx")
seven <- read_excel("features/full_new7.xlsx")

features_new <- bind_rows(one, two, three, four, five, six, seven)

```

```{r}

write_xlsx(x = features_new, path = "features_full.xlsx", col_names = TRUE)

```

```{r}
full_data_df <- read_excel("updated_full_df.xlsx")
new_full_df <- bind_cols(full_data_df, features_new)
write_xlsx(x = new_full_df, path = "final_df.xlsx", col_names = TRUE)

```

## get data frame set up
```{r}
features_data <- data.frame()
```

```{r read_data}
full_data <- read_excel("webscrape_features.xlsx")
```

### turn urls into vector

```{r url_vector}
vector_url_combined <- as.vector(unlist(full_data['full_url']))
```

###Loop through url

```{r create_loop}
##loops through the rows -- each url
  i = 1
for(value in vector_url_combined){
  #print(antwerp_engraver_url_data[i, ])
  #antwerp_engraver_link = antwerp_engraver_url_data[i, ]

  print(value)
  #print("count")
  print(i)
  i = i+1
  
  emanuel = read_html(value) #read's html of each link page
  
  #occupation address
  location <- emanuel  %>% 
  html_nodes(css = "ul:nth-child(12)") %>% 
  html_text() %>% 
  as_tibble() 
  
birth <- emanuel  %>% 
  html_nodes(css = "div+ table tr:nth-child(3) td+ td") %>% 
  html_text() %>% 
  as_tibble() 

death <- emanuel  %>% 
  html_nodes(css = "div+ table tr:nth-child(4) td+ td") %>% 
  html_text() %>% 
  as_tibble() 

#marriage
marriage <- emanuel  %>% 
  html_nodes(css = "ul:nth-child(6)") %>% 
  html_text() %>% 
  as_tibble() 
  
  #occupations
  occupation <- emanuel  %>% 
    html_nodes(css = "ul:nth-child(10)") %>% 
    html_text() %>% 
    as_tibble() 
  
##convert into data set
  temp_data <- bind_cols(occupation, birth, death, location, marriage, value)

  temp_data <- temp_data %>% 
    rename(
      occupation = value...1,
      birth_place = value...2,
      death_place = value...3,
      locations = value...4, 
      marriage = value...5,
      url = ...6
    )

  ##bind to actual dataset
  features_data <- bind_rows(features_data, temp_data)
Sys.sleep(2)

}

```

```{r}
write_xlsx(x = features_data, path = "full_new7.xlsx", col_names = TRUE)

```
