---
title: "updatedFeatures"
author: "Grace Gao"
date: "3/16/2021"
output: html_document
---
## R Markdown
```{r packages}
library("readxl")
library(tidyverse)
library('xml2')
library(rvest)
library(openxlsx)
library(readxl)
library(writexl)
library(dplyr)

```
## R Markdown
```{r packages}
library("readxl")
library(tidyverse)
library('xml2')
library(rvest)
library(openxlsx)
library(readxl)
library(writexl)
library(dplyr)

```

## get data frame set up
```{r}
features_data <- data.frame()
```

```{r read_data}
full_data <- read_excel("updated_full_df.xlsx")
```

### turn urls into vector

```{r url_vector}
vector_url_combined <- as.vector(unlist(full_data['full_url']))
```

###Loop through url

```{r create_loop}
##loops through the rows -- each url
  i = 1
for(value in vector_url_combined){
  #print(antwerp_engraver_url_data[i, ])
  #antwerp_engraver_link = antwerp_engraver_url_data[i, ]

  print(value)
  #print("count")
  print(i)
  i = i+1
  
  emanuel = read_html(value) #read's html of each link page
  
  #using the computer extension 

birthlocation <- emanuel  %>% 
  html_nodes(css = "tr:nth-child(3) a") %>% 
  html_text() %>% 
  as_tibble() 


deathlocation <- emanuel  %>% 
  html_nodes(css = "tr:nth-child(4) a") %>% 
  html_text() %>% 
  as_tibble() 
  

##convert into data set
  temp_data <- bind_cols(birthlocation, deathlocation, value)

  temp_data <- temp_data %>% 
    rename(
      birthLocation = value...1,
      deathLocation = value...2,
      url = ...3
    )

  ##bind to actual dataset
  features_data <- bind_rows(features_data, temp_data)
Sys.sleep(2)

}

```

```{r}
write_xlsx(x = features_data, path = "fixed_location.xlsx", col_names = TRUE)

````

### occupation address webscrape
```{r}
emanuel <-  read_html("http://www.vondel.humanities.uva.nl/ecartico/persons/3160")
features_data <- data.frame()

```


```{r}
#using the computer extension 

birthlocation <- emanuel  %>% 
  html_nodes(css = "tr:nth-child(3) a") %>% 
  html_text() %>% 
  as_tibble() 
birthlocation
```

```{r}
#using the computer extension 

location <- emanuel  %>% 
  html_nodes(css = "tr:nth-child(4) a") %>% 
  html_text() %>% 
  as_tibble() 
location
```