---
title: "ocupational_address"
author: "Grace Gao"
date: "3/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r packages}
library("readxl")
library(tidyverse)
library('xml2')
library(rvest)
library(openxlsx)
library(readxl)
library(writexl)
library(dplyr)

```

### occupation address webscrape
```{r}
emanuel <-  read_html("http://www.vondel.humanities.uva.nl/ecartico/persons/3160")
features_data <- data.frame()

```


```{r}
#using the computer extension 

location <- emanuel  %>% 
  html_nodes(css = "ul:nth-child(12)") %>% 
  html_text() %>% 
  as_tibble() 
location
```
#marraige
```{r}
#using the computer extension 

marriage <- emanuel  %>% 
  html_nodes(css = "ul:nth-child(6)") %>% 
  html_text() %>% 
  as_tibble() 
marriage
```

#Death and Birth Place
```{r}
#using the computer extension 

birth <- emanuel  %>% 
  html_nodes(css = "div+ table tr:nth-child(3) td+ td") %>% 
  html_text() %>% 
  as_tibble() 
birth

death <- emanuel  %>% 
  html_nodes(css = "div+ table tr:nth-child(4) td+ td") %>% 
  html_text() %>% 
  as_tibble() 
death

```

#occupation
```{r}
#using the computer extension 

occupation <- emanuel  %>% 
  html_nodes(css = "ul:nth-child(10)") %>% 
  html_text() %>% 
  as_tibble() 
occupation

```


##convert excel

```{r}
temp_data <- bind_cols(occupation, birth, death, location, marriage, value)

temp_data <- temp_data %>% 
  rename(
     occupation = value...1,
    birth_place = value...2,
    death_place = value...3,
    locations = value...4, 
    marriage = value...5,
    url = ...6
    )
features_data <- bind_rows(features_data, temp_data)
glimpse(features_data)
```

```{r}
write_xlsx(x = features_data, path = "temp.xlsx", col_names = TRUE)

```
