---
title: "amsterdam_book_data"
author: "Grace Gao"
date: "12/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

http://www.vondel.humanities.uva.nl/ecartico/persons/index.php?occupation_id=28%2C663%2C29%2C658%2C32%2C30%2C1028%2C243&subjectmat=&place=Amsterdam&gender=male&year_start=1506&year_end=1725&formtype=selections&page=1&subtask=selections
http://www.vondel.humanities.uva.nl/ecartico/persons/index.php?occupation_id=28%2C663%2C29%2C658%2C32%2C30%2C1028%2C243&subjectmat=&place=Amsterdam&gender=male&year_start=1506&year_end=1725&formtype=selections&page=38&subtask=selections

```{r importing_libraries}
library(broom)
library(tidyverse)
library(readr)
library(tidyr)
library(stringr)
library(dplyr)
library(rvest)
library(xlsx)
library(writexl)
```

###Read in CSV file for url data
```{r opening_data}
amsterdam_book_url_data <- read_csv("data/amsterdam_book_url.csv")
```

###Create a dataframe

```{r create_dataframe}
amsterdam_book_df = data.frame()

```


### Create the loop
This section will loop through each url in the dataframe
```{r convert_vector}

vector_book_amsterdam <- as.vector(unlist(amsterdam_book_url_data['full_url']))

```

```{r create_loop}
##loops through the rows -- each url
for(value in vector_book_amsterdam){
  #print(antwerp_engraver_url_data[i, ])
  #antwerp_engraver_link = antwerp_engraver_url_data[i, ]
  #print(value)
  results_amsterdam_book = read_html(value) #read's html of each link page
  
  ##getting text
  names_amsterdam_book <- results_amsterdam_book %>% 
  html_nodes("li") %>% 
  html_text()
  
  ##parsing individual link
  url_amsterdam_book <- results_amsterdam_book %>% 
  html_nodes("li a") %>% 
  html_attr("href")
  
  ##puts the url and names into a tibble
  results_df_amsterdam_book <- tibble(names_amsterdam_book, url_amsterdam_book)
  
  #remove first four rows
  results_df_amsterdam_book <- results_df_amsterdam_book[-c(1,2,3,4),]
  
  #bind the url to the final dataset
  amsterdam_book_df = bind_rows(amsterdam_book_df, results_df_amsterdam_book)
  
}


```

###Mutating the urls to get final url
```{r fix_theurl}
amsterdam_book_df <- amsterdam_book_df %>% 
  mutate(base_url = "http://www.vondel.humanities.uva.nl") %>% 
  mutate(full_url = glue::glue("{base_url}{url_amsterdam_book}")) %>% 
  mutate(full_url = str_replace_all(full_url, "\\.\\.", ""))

amsterdam_book_df

```



###Export data into Excel
```{r export_data}
#write_xlsx(x = amsterdam_book_df, path = "amsterdam_book_data.xlsx", col_names = TRUE)

```



###Female Book

###Create a dataframe

```{r create_dataframe}
amsterdam_book_df = data.frame()

```

### Create Vectors 
```{r women_url}

vector_book_amsterdam_fem <- c("http://www.vondel.humanities.uva.nl/ecartico/persons/index.php?occupation_id=28%2C663%2C29%2C658%2C32%2C30%2C1028%2C243&subjectmat=&place=Amsterdam&gender=female&year_start=1506&year_end=1725&formtype=selections&page=1&subtask=selections", "http://www.vondel.humanities.uva.nl/ecartico/persons/index.php?occupation_id=28%2C663%2C29%2C658%2C32%2C30%2C1028%2C243&subjectmat=&place=Amsterdam&gender=female&year_start=1506&year_end=1725&formtype=selections&page=2&subtask=selections", "http://www.vondel.humanities.uva.nl/ecartico/persons/index.php?occupation_id=28%2C663%2C29%2C658%2C32%2C30%2C1028%2C243&subjectmat=&place=Amsterdam&gender=female&year_start=1506&year_end=1725&formtype=selections&page=3&subtask=selections")

```



### Create the loop


```{r create_loop}
##loops through the rows -- each url
for(value in vector_book_amsterdam_fem){
  #print(antwerp_engraver_url_data[i, ])
  #antwerp_engraver_link = antwerp_engraver_url_data[i, ]
  #print(value)
  results_amsterdam_book = read_html(value) #read's html of each link page
  
  ##getting text
  names_amsterdam_book <- results_amsterdam_book %>% 
  html_nodes("li") %>% 
  html_text()
  
  ##parsing individual link
  url_amsterdam_book <- results_amsterdam_book %>% 
  html_nodes("li a") %>% 
  html_attr("href")
  
  ##puts the url and names into a tibble
  results_df_amsterdam_book <- tibble(names_amsterdam_book, url_amsterdam_book)
  
  #remove first four rows
  results_df_amsterdam_book <- results_df_amsterdam_book[-c(1,2,3,4),]
  
  #bind the url to the final dataset
  amsterdam_book_df = bind_rows(amsterdam_book_df, results_df_amsterdam_book)
  
}


```

###Mutating the urls to get final url
```{r fix_theurl}
amsterdam_book_df <- amsterdam_book_df %>% 
  mutate(base_url = "http://www.vondel.humanities.uva.nl") %>% 
  mutate(full_url = glue::glue("{base_url}{url_amsterdam_book}")) %>% 
  mutate(full_url = str_replace_all(full_url, "\\.\\.", ""))

amsterdam_book_df

```



###Export data into Excel
```{r export_data}
write_xlsx(x = amsterdam_book_df, path = "amsterdam_book_fem_data.xlsx", col_names = TRUE)

```



