---
title: "painters_url_antwerp"
author: "Grace Gao"
date: "12/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Import a webpage using `read_html` Antwerp - Engravers and Etchers: Male - pg 2

```{r get_pagetwobookurl}
results_antwerp_painters_url <- read_html("http://www.vondel.humanities.uva.nl/ecartico/persons/index.php?occupation_id=130%2C209&subjectmat=&place=antwerpen&gender=male&year_start=1556&year_end=1725&formtype=selections&page=1&subtask=selections")

#results_antwerp_engraver
```


```{r}
results_antwerp_painters_url %>% 
  html_nodes("div.subnav a") %>% 
  html_text()

```

```{r loop}
navigation_painter <- results_antwerp_painters_url %>% 
  html_nodes("div.subnav a") %>% 
  html_attr("href")

navigation_painter
```

```{r}
nav_df_painter <- tibble(navigation_painter)
nav_df_painter

#http://www.vondel.humanities.uva.nl/ecartico/persons/index.php?occupation_id=130%2C209&subjectmat=&place=antwerpen&gender=male&year_start=1556&year_end=1725&formtype=selections&page=1&subtask=selections
#http://www.vondel.humanities.uva.nl/ecartico/persons/index.php?occupation_id=130%2C209&subjectmat=&place=antwerpen&gender=male&year_start=1556&year_end=1725&formtype=selections&page=2&subtask=selections
```
```{r}
nav_df_painter <- nav_df_painter %>%
  filter(str_detect(navigation_painter, "&page=")) %>%
  distinct(navigation_painter) %>%
  mutate(page_no = str_extract(navigation_painter, "\\d+$")) %>%
  mutate(page_no = as.numeric(page_no))

nav_df_painter
```

```{r}
nav_df_engraver <- nav_df_engraver %>% 
  mutate(base_url = "http://www.vondel.humanities.uva.nl") %>% 
  mutate(full_url = glue::glue("{base_url}{navigation_engraver}")) %>% 
  mutate(full_url = str_replace_all(full_url, "\\.\\.", ""))
nav_df_engraver

for(page_num in 1:42){
  
}


```



### Converting tibbles into Excel Files

```{r create_excel}
#write_xlsx(x = nav_df_engraver, path = "antwerp_engraver_url.xlsx", col_names = TRUE)
```